id: model_mlperf_tiny_vww_int8
description: MLPerf Tiny visual wakeword reference model for int8
model:
  source: prebuilt
  path: vision/mlperf-tiny/vww/model.tflite
test:
  tolerance: 10
  golden_data: vision/mlperf-tiny/vww/golden.npz
