id: model_dfnet2_int16x8
description: DeepFilterNet2 streaming speech enhancement model for int16
platforms:
  - apollo510_evb
model:
  source: prebuilt
  path: audio/dfnet2/model.tflite
test:
  tolerance: 10
  golden_data: audio/dfnet2/golden.npz
  fvp_timeout_seconds: 600
