id: model_mlperf_tiny_ad01_int8
description: MLPerf Tiny anomaly detection reference model for int8
model:
  source: prebuilt
  path: anomaly-detection/mlperf-tiny/ad01/model.tflite
test:
  tolerance: 10
  golden_data: anomaly-detection/mlperf-tiny/ad01/golden.npz
