id: model_wav2letter_int8
description: Wav2Letter pruned int8 model
platforms:
  - apollo510_evb
model:
  source: prebuilt
  path: audio/wav2letter/model.tflite
test:
  tolerance: 10
  golden_data: audio/wav2letter/golden.npz
  fvp_timeout_seconds: 600
memory:
  tensors:
    - kind: constant
      memory: psram
    - kind: persistent
      memory: psram
