id: model_rnnoise_int8
description: RNNoise int8 model
platforms:
  - apollo510_evb
model:
  source: prebuilt
  path: audio/rnnoise/model.tflite
test:
  tolerance: 10
  golden_data: audio/rnnoise/golden.npz
  fvp_timeout_seconds: 600
